config/routes.rb
Rails.application.routes.draw do
  resources :procedures
  resources :designers

  namespace :api do
  	resources :common_codes, only: :index

  	resources :designers, only: :index do
      collection do
        post :modify
        post :authentication
        post :signup
        post :signin
      end
    end
  end



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
end

app/models/designer.rb
class Designer < ApplicationRecord
  has_one :image, as: :imageable
  has_many :designer_auths
  has_many :procedures

  def self.available_email(email)
    find_by(email: email).nil? if email.present?
  end

  def self.existed_designer(email, password)
    find_by(email: email, password: password) if (email && password).present?
  end
end

app/controllers/api/designers_controller.rb
module Api
  class DesignersController < ApplicationController
    before_action :set_designer_auth, only:
      [:index, :modify, :authentication]
    #   :presentations, :favorite_presentations]
    #   :reviews, :review_update, :review_destroy]

    # before_action :set_review, only:
    #  [:review_update, :review_destroy]

    skip_before_filter :verify_authenticity_token, only:
      [:create, :authentication, :signup, :signin]
    #   :presentations, :favorite_presentations]
    #   :reviews, :review_update, :review_destroy]

    def index
      # 사용자 인증이 안되면 에러 제이선 출력
      if @designer_auth.present?
        @designer = @designer_auth.designer
        # else
        # ErrorHelper.error_handling(
        #    '사용자 인증 실패', '존재하지 않는 사용자입니다.'
        # )
        # render "error.json.jbuilder"
      end
    end

    def modify
      # 사용자 인증이 안되면 에러 제이선 출력
      if @designer_auth.designer.present?
        @designer = @designer_auth.designer
        add_designer_param(@designer)
        ImageHelper.update_single_image(params[:image], @designer)
        @designer.save!
      end
    end

    def authentication
      # 사용자 인증이 안되면 에러 제이선 출력
      if @designer_auth.designer.present?
        @token = DesignersHelper.gen_designer_auth(@designer_auth.designer).access_token
      end
    end

    def signup
      # 사용자 로그인 모든 파라미터 nil 여부 체크 필요
      if Designer.available_email(params[:email])
        @designer = Designer.new
        add_designer_param(@designer)
        ImageHelper.create_single_image(params[:image], @designer)
        @designer.save!
        @token = DesignersHelper.gen_designer_auth(@designer).access_token
      end
    end

    def signin
      # 로그인 실패할 경우 제이선 에러 출력
      @designer = Designer.existed_designer(params[:email], params[:password])
      if @designer.present?
        DesignersHelper.gen_designer_auth(@designer)
        @designer.save!
      end
    end

    #def presentations
    #  # 사용자 인증이 안되면 에러 제이선 출력
    #  if @user_auth.user.present?
    #    @user = @user_auth.user
    #    @user_presentations = @user.presentations.all.order(created_at: :DESC)
    #  end
    #end

    #def favorite_presentations
    #  if @user_auth.user.present?
    #    @user = @user_auth.user
    #    @user_favorites = @user.favorites
    #  end
    #end

    private

    def add_designer_param(designer)
      designer.email = params[:email]
      designer.password = params[:password]
      designer.nickname = params[:nickname]
    end

    def set_designer_auth
      @designer_auth = DesignerAuth.find_by_access_token(params[:access_token])
    end
  end
end

app/controllers/designers_controller.rb
class DesignersController < ApplicationController
  before_action :set_designer, only: [:show, :edit, :update, :destroy]

  respond_to :html, :json

  # GET /designers
  # GET /designers.json
  def index
    @designers = Designer.all
    respond_with(@designers)
  end

  # GET /designers/1
  # GET /designers/1.json
  def show
    respond_with(@designer)
  end

  # GET /designers/new
  def new
    @designer = Designer.new
    respond_with(@designer)
  end

  # GET /designers/1/edit
  def edit
  end

  # POST /designers
  # POST /designers.json
  def create
    @designer = Designer.new(designer_params)
    ImageHelper.create_single_image(params[:image], @designer)
    @designer.save
    DesignersHelper.gen_designer_auth(@designer).access_token
    respond_with(@designer)
  end

  # PATCH/PUT /designers/1
  # PATCH/PUT /designers/1.json
  def update
    @designer.update(designer_params)
    ImageHelper.update_single_image(params[:image], @designer)
    respond_with(@designer)
  end

  # DELETE /designers/1
  # DELETE /designers/1.json
  def destroy
    @designer.destroy
    respond_with(@designer)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_designer
      @designer = Designer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def designer_params
      params.require(:designer).permit(:email, :password, :nickname, :image)
    end
end

app/helpers/api/designers_helper.rb
module Api::DesignersHelper
  def self.gen_designer_auth(designer)
    access_token = get_access_token(designer)
    access_token = get_access_token(designer) while duplicated(access_token)
    DesignerAuth.create(designer_id: designer.id, access_token: access_token)
  end

  def self.duplicated(access_token)
    DesignerAuth.all.find_by_access_token(access_token).present?
  end

  def self.get_access_token(designer)
    id = designer.id
    pw = designer.password
    realm = Digest::SHA1.hexdigest(SecureRandom.base64)
    Digest::MD5.hexdigest([id, realm, pw].join(':'))
  end
end

app/helpers/designers_helper.rb
module DesignersHelper
end

app/views/designers/_form.html.erb
<%= form_for @designer, html: { multipart: true } do |f| %>
  <% if designer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(designer.errors.count, "error") %> prohibited this designer from being saved:</h2>

      <ul>
      <% designer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :image %>
    <%= file_field_tag :image %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <%= f.text_field :password %>
  </div>

  <div class="field">
    <%= f.label :nickname %>
    <%= f.text_field :nickname %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/designers/edit.html.erb
<h1>Editing Designer</h1>

<%= render 'form', designer: @designer %>

<%= link_to 'Show', @designer %> |
<%= link_to 'Back', designers_path %>

app/views/designers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Designers</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Image Thumbnail</th>
      <th>Email</th>
      <th>Password</th>
      <th>Nickname</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @designers.each do |designer| %>
      <tr>
        <td><%= designer.id %></td>
        <td align="center">
          <% if designer.image.present? %>
            <img src= <%= designer.image.image.url %> width="100" height="100">
          <% else %>
            이미지 없음
          <% end %> 
        </td>
        <td><%= designer.email %></td>
        <td><%= designer.password %></td>
        <td><%= designer.nickname %></td>
        <td><%= link_to 'Show', designer %></td>
        <td><%= link_to 'Edit', edit_designer_path(designer) %></td>
        <td><%= link_to 'Destroy', designer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Designer', new_designer_path %>

app/views/designers/new.html.erb
<h1>New Designer</h1>

<%= render 'form', designer: @designer %>

<%= link_to 'Back', designers_path %>

app/views/designers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @designer.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @designer.password %>
</p>

<p>
  <strong>Nickname:</strong>
  <%= @designer.nickname %>
</p>

<%= link_to 'Edit', edit_designer_path(@designer) %> |
<%= link_to 'Back', designers_path %>