config/routes.rb
Rails.application.routes.draw do
  resources :procedures
  resources :designers

  namespace :api do
  	resources :common_codes, only: :index

  	resources :designers, only: :index do
      collection do
        post :modify
        post :authentication
        post :signup
        post :signin
      end
    end
  end



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
end

app/models/procedure.rb
class Procedure < ApplicationRecord
  belongs_to :designer
  has_many :procedure_categories
end

app/controllers/procedures_controller.rb
class ProceduresController < ApplicationController
  before_action :set_procedure, only: [:show, :edit, :update, :destroy]

  respond_to :html, :json

  # GET /procedures
  # GET /procedures.json
  def index
    @procedures = Procedure.all
    respond_with(@procedures)
  end

  # GET /procedures/1
  # GET /procedures/1.json
  def show
    respond_with(@procedure)
  end

  # GET /procedures/new
  def new
    @procedure = Procedure.new
    respond_with(@procedure)
  end

  # GET /procedures/1/edit
  def edit
  end

  # POST /procedures
  # POST /procedures.json
  def create
    @procedure = Procedure.new(procedure_params)
    @procedure.save
    respond_with(@procedure)
  end

  # PATCH/PUT /procedures/1
  # PATCH/PUT /procedures/1.json
  def update
    @procedure.update(procedure_params)
    respond_with(@procedure)
  end

  # DELETE /procedures/1
  # DELETE /procedures/1.json
  def destroy
    @procedure.destroy
    respond_with(@procedure)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_procedure
      @procedure = Procedure.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def procedure_params
      params.require(:procedure).permit(:designer_id, :title, :subtitle, :content)
    end
end

app/helpers/procedures_helper.rb
module ProceduresHelper
end

app/views/procedures/_form.html.erb
<%= form_for(procedure) do |f| %>
  <% if procedure.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(procedure.errors.count, "error") %> prohibited this procedure from being saved:</h2>

      <ul>
      <% procedure.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :designer_id %>
    <%= f.text_field :designer_id %>
  </div>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_area :title %>
  </div>

  <div class="field">
    <%= f.label :subtitle %>
    <%= f.text_area :subtitle %>
  </div>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/procedures/edit.html.erb
<h1>Editing Procedure</h1>

<%= render 'form', procedure: @procedure %>

<%= link_to 'Show', @procedure %> |
<%= link_to 'Back', procedures_path %>

app/views/procedures/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Procedures</h1>

<table>
  <thead>
    <tr>
      <th>Designer</th>
      <th>Title</th>
      <th>Subtitle</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @procedures.each do |procedure| %>
      <tr>
        <td><%= procedure.designer %></td>
        <td><%= procedure.title %></td>
        <td><%= procedure.subtitle %></td>
        <td><%= procedure.content %></td>
        <td><%= link_to 'Show', procedure %></td>
        <td><%= link_to 'Edit', edit_procedure_path(procedure) %></td>
        <td><%= link_to 'Destroy', procedure, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Procedure', new_procedure_path %>

app/views/procedures/new.html.erb
<h1>New Procedure</h1>

<%= render 'form', procedure: @procedure %>

<%= link_to 'Back', procedures_path %>

app/views/procedures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Designer:</strong>
  <%= @procedure.designer %>
</p>

<p>
  <strong>Title:</strong>
  <%= @procedure.title %>
</p>

<p>
  <strong>Subtitle:</strong>
  <%= @procedure.subtitle %>
</p>

<p>
  <strong>Content:</strong>
  <%= @procedure.content %>
</p>

<%= link_to 'Edit', edit_procedure_path(@procedure) %> |
<%= link_to 'Back', procedures_path %>